In [11]:
# Numpyライブラリの読み込み
import numpy as np

array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)

# 要素のデータ型
print(array.dtype)

#要素数
print(array.size)

# 次元数
print(array.ndim)

# 配列の全要素を2で割る
div_array = array/2
print(div_array)

# 一番目の配列の一番目の要素を抽出し、2で割る
div_array2 = array[0][0]/2
print(div_array2)

#配列のフラット化
flatten_array = array.flatten()
print(flatten_array)

# ゼロ配列の生成
zero_array = np.zeros(9)
print(zero_array)

# numpy配列をリストへ変換
list = array.tolist()
print(list)
print(type(list))

# リストをnumpy配列へ変換
array = np.array(list)
print(array)
print(type(array))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int64
9
2
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
0.5
[1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
